name: "Auto-merge Update Versions Pull Request"
on:
  check_run:
    types: [completed]

jobs:
  merge-successful-version-update-pr:
    name: Auto-merge Update Versions Pull Request
    runs-on: ubuntu-latest
    if: github.event.check_run.conclusion == 'success'

    steps:
      - name: Check PR Status
        env:
          CHECK_RUN: github.event.check_run
        run: |
          jq <<<"${CHECK_RUN:?}"
