name: "Build the Mythril Container Images for linux/amd64 and linux/arm64"
on:
  pull_request:
    branches:
      - main
    paths:
      - "docker/*"

env:
  REGISTRY: ghcr.io
  TAG_PREFIX: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2a1a44ac4aa01993040736bd95bb470da1a38365

      - name: Extract Locked Dependency Version Variables
        uses: docker/bake-action@ad0d2a9712378c502a7d5c590deb0d7a02d2a61d
        with:
          workdir: ./docker
          files: docker-bake.hcl
          targets: locked-versions
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Build & Test
        uses: docker/bake-action@ad0d2a9712378c502a7d5c590deb0d7a02d2a61d
        with:
          workdir: ./docker
          files: docker-bake.hcl,locked-versions/docker-bake.versions.json,base-images.lock
          provenance: true
          sbom: true
          push: false
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
